/** @type {import('next').NextConfig} */
const routes = [
  "testing-new-blog",
  "everyday-habits-that-cause-teeth-staining",
  "how-do-you-make-your-dentures-last-long",
  "how-to-find-the-best-family-dentist",
  "the-procedure-for-root-canal",
  "5-life-changing-benefits-of-cosmetic-dentistry",
  "the-benefits-of-same-day-crowns",
  "most-common-types-of-dental-implants",
  "benefits-of-invisalign-over-regular-braces",
  "what-to-expect-from-dental-veneers-procedure",
  "types-of-teeth-whitening-procedures",
  "preventive-dentistry-treatments",
  "who-is-the-best-candidate-for-dental-implants",
  "what-are-the-benefits-of-mobile-dentistry",
  "different-types-of-dentures-and-their-functions",
  "why-is-it-necessary-to-have-a-family-dentist",
  "who-needs-root-canal-therapy",
  "what-is-preventive-dentistry",
  "what-is-cosmetic-dentistry",
  "why-should-you-visit-the-dentist-regularly",
  "why-you-may-need-invisalign-aligners",
  "what-are-dentures",
  "advantages-and-disadvantages-of-all-on-4-dental-implants",
  "fighting-chronic-bad-breath",
  "sedation-dentistry",
  "restorative-dentistry",
  "procedure-for-all-on-4-dental-implants",
  "how-do-fixed-bridges-work",
  "dental-veneer",
  "benefits-of-dental-crowns",
  "top-5-benefits-of-composite-fillings",
  "what-is-an-invisalign-treatment",
  "how-is-a-root-canal-procedure-done",
  "helen-and-her-family-in-ukraine",
  "orthodontic-treatments",
  "who-is-eligible-for-teeth-whitening",
  "when-should-you-get-dentures",
  "how-do-dental-sealants-work",
  "do-i-need-dental-inlays-or-onlays",
  "dont-let-your-end-of-year-benefits-go-to-waste",
  "dental-anxiety",
  "toothache-remedies",
  "message-to-our-patients-all-patients-are-still-required-to-wear-mask",
  "what-are-cerec-crowns",
  "clean-teeth-can-boost-your-immune-system",
  "invisalign-step-by-step-procedure",
  "5-facts-you-need-to-know-about-invisalign",
  "how-to-manage-dentist-anxiety-in-children",
  "covid-19-protocols-and-pre-screening-updates",
  "festive-foods-the-dos-and-dont-this-holiday-season",
  "top-3-benefits-of-a-local-dentist",
  "chewing-gum-the-gum-the-bad-and-the-ugly",
  "fang-tastic-halloween-5-simple-tricks-to-scare-cavities-away-during-halloween",
  "cerec-same-day-crowns",
  "procopio-towle-dental-office-remodel-and-modified-hours",
  "the-importance-of-regular-teeth-cleaning",
  "wheres-the-filling",
  "procopio-towle-dental-office-newsletter",
  "the-step-by-step-guide-to-dentures",
  "how-does-the-dental-implant-procedure-work",
  "the-differences-between-dental-fillings-and-dental-sealants",
  "dental-fillings-procedures-in-walnut-creek",
  "root-canals-causes-problems-and-treatments",
  "dental-sealant-benefits-causes-and-side-effects",
  "all-you-need-to-know-about-dental-crowns",
  "dental-practice-re-opening-monday-june-1st-2020",
  "benefits-of-a-family-dentistry",
  "remembering-dr-wolter-from-our-patients",
  "dr-wolters-death-anniversary-message",
  "procopio-towle-dental-office-extended-protocols",
  "how-to-manage-tooth-ache-during-covid-isolation",
  "4-29-2020-shelter-in-place-extension-update-from-procopio-dental-office",
  "dr-procopios-covid-19-update",
  "gum-disease-why-routine-check-ups-are-essential",
  "extended-protocols-due-to-covid-19",
  "dental-emergencies",
  "4-1-2020-update-from-procopio-towle-dental-office-about-covid-19",
  "benefits-of-dental-implants",
  "an-update-from-procopio-towle-dental-office-about-covid-19",
  "a-message-from-procopio-towle-dental-office-about-covid-19",
  "the-benefits-of-preventive-dentistry",
  "canned-non-perishable-food-drive",
];
const servicesRoutes = [
  "cosmetic-dentistry",
  "crowns-bridges",
  "dental-implants",
  "dentures",
  "family-dentistry",
  "invisalign",
  "preventive-dentistry",
  "root-canals",
  "same-day-crowns",
  "teeth-whitening",
];

const nextConfig = {

  reactStrictMode: true,
  swcMinify: true,
  async redirects() {
    return (
      // servicesRoutes.map((route) => {
      //   return {
      //     source: `/${route}`,
      //     destination: `/services/${route}`,
      //     permanent: true,
      //   };
      // }),
      
      routes.map((route) => {
        return {
          source: `/${route}`,
          destination: `/dental-articles-news/${route}`,
          permanent: true,
        };
      })
    );
  },
};
module.exports = nextConfig;
